### ISSUE TITLE
Some thesis suggestions

### ISSUE THREAD

**Issue by gkorpal** [jack4818/maths-theses#1]
- [Fast Algorithms for Towers of Finite Fields and Isogenies](https://hal.inria.fr/tel-00547034) by Luca De Feo
- [Exploring Isogeny Graphs](https://defeo.lu/hdr/#manuscript) by Luca De Feo (Habilitation)
- [Isogenies of Elliptic Curves: A Computational Approach](https://www.sagemath.org/files/thesis/shumow-thesis-2009.pdf) by Daniel Shumow (Masters)
- [Number Theoretic Algorithms For Elliptic Curves](https://drum.lib.umd.edu/handle/1903/8456) by Juliana V. Belding
- [Isogeny graphs, modular polynomials, and applications](https://martindale.info/research/Thesis.pdf) by Chloe Martindale
- [Efficient algorithms for abelian varieties and their moduli spaces](https://www.normalesup.org/~robert/pro/publications/academic/hdr.pdf) by Damien Robert (Habilitation)

**Comment by gkorpal** [comment]
Forgot to add Waterhouse's thesis at Harvard, which was published in a journal:

- [Abelian varieties over finite fields](https://eudml.org/doc/81852) by William C. Waterhouse

**Comment by GiacomoPope** [comment]
Nice, these all look interesting thanks for contributing

**Comment by gkorpal** [comment]
Reference from Castryck-Decru attack paper:
- [Superspecial curves of genera two and three](https://www.proquest.com/pagepdf/304100343) by Bradley Brock

**Comment by GiacomoPope** [comment]
Thanks! Added
